name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

env:
  RUNTIME: ~/.bun/bin/bun
  RUNTIMEX: ~/.bun/bin/bunx

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Bun runtime
        run: curl -fsSL https://bun.sh/install | bash

      - name: Install dependencies
        run: make install

      - name: Run hardhat tests
        run: make hardhat-test
