name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

jobs:
  bun-build-test:
    runs-on: ubuntu-latest
    env:
      PACKAGE_MANAGER: ~/.bun/bin/bun
      PACKAGE_EXECUTOR: ~/.bun/bin/bunx
    steps:
      - uses: actions/checkout@v3

      - name: Install Bun runtime
        run: curl -fsSL https://bun.sh/install | bash

      - name: Install dependencies
        run: make install

      - name: Run hardhat tests
        run: make hardhat-test

  npm-build-test:
    runs-on: ubuntu-latest
    env:
      USE: npm
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: make install

      - name: Run hardhat tests
        run: make hardhat-test

  yarn-build-test:
    runs-on: ubuntu-latest
    env:
      USE: yarn
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: make install

      - name: Run hardhat tests
        run: make hardhat-test
